[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Viktor Zepeda", email = "vza12@sfu.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "elevenlabs>=2.70.0",
    "fastapi[standard]>=0.141.1",
    "google-ai-generativelanguage==0.6.2",
    "google-api-core==2.19.0",
    "google-api-python-client==2.127.0",
    "google-auth==2.29.0",
    "google-auth-httplib2==0.2.0",
    "google-genai==1.10.0",
    "python-dotenv==1.2.2",
    "requests==2.34.2",
    "urllib3==2.7.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
